### ISSUE TITLE
Crash after entering Nextcloud instance url

### ISSUE THREAD

**Issue by A-wels** [YehonatanVishna/Podcast-Merlin--Nextcloud-Gpodder-Client-For-Windows#1]
After entering the url for my nextcloud instance (https://example.mynextclouddomain.xyz), the programm crashes without error message.

**Comment by CalAlaera** [comment]
Same problem here. I'm asked for my instance URL (doesn't matter whether I give it the IP address or the hostname, with or without https:// on the front). I press ok, and the app just quits. No error messages, and no logs generated as far as I can tell.

**Comment by Patriot2407** [comment]
+1 same issue

**Comment by YehonatanVishna** [comment]
Hey, I was on a vacation for the last month, I would push a fix as soon as I get home

**Comment by YehonatanVishna** [comment]
hey, I tried to fix the issue you had, and I can't replicate it on my own windows 11 machine and windows 10 vm. Could you Write for me steps it takes to replicate this crash?

**Comment by CalAlaera** [comment]
1. Install Podcast Merlin from the Windows Store
2. Run Podcast Merlin, this screen appears ![Clipboard01](https://github.com/YehonatanVishna/Podcast-Merlin--Nextcloud-Gpodder-Client-For-Windows/assets/59891537/48ad086f-52f1-45b7-8a1a-23228c84e080)
3. Input http://10.15.20.25/ (or http://nextcloudpi.local/ or https://10.15.20.25/ or https://nextcloudpi.local/ )
4. Podcast Merlin exits with no error message.

**Comment by YehonatanVishna** [comment]
did you write the port number in your url?

**Comment by CalAlaera** [comment]
Just tried http://10.15.20.25:80/ and other combinations. Same result, no error message.

**Comment by YehonatanVishna** [comment]
The new 1.0.5 release just made it to the store. Please check whether the issue is fixed.

**Comment by CalAlaera** [comment]
Issue is now fixed for me, thanks.

I had to input http://10.15.20.25:80/index.php for it to work, but got there in the end. :)

**Comment by corellon1** [comment]
I have version 1.0.5 installed and have the same problem.

**Comment by YehonatanVishna** [comment]
have you tried entering the full url including the /index.php ?

**Comment by corellon1** [comment]
> have you tried entering the full url including the /index.php ?

Thank you, it works. Thank you for your work and your help.

**Comment by A-wels** [comment]
Including /index.php worked for me as well!
