### ISSUE TITLE
How to build yourself

### ISSUE THREAD

**Issue by A-wels** [YehonatanVishna/Podcast-Merlin--Nextcloud-Gpodder-Client-For-Windows#2]
Could you provide some hints how I could build the program myself? E.g. which tools are needed

**Comment by YehonatanVishna** [comment]
This is a universal windows program, you need to use visual studio 2022 and to download the universal windows workflow at setup

**Comment by A-wels** [comment]
Alright, thanks! Will try to figure out a way on linux

**Comment by YehonatanVishna** [comment]
I would be thriled if you would find a way to run my app on linux. I tried it myself, but I could find a way to run UWP apps on linux (even using wine). 
For listening to podcasts on my linux install, I use KDE kasts, which also has NextCloud Gpodder support.
